name: diabetist_pro
description: Diabetist Application, created by Mahdi Pishguy pishguy@gmail.com

version: 1.0.0+1
environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  states_rebuilder: ^1.1.0
  json_annotation: ^2.4.0
  provider: ^3.0.0+1
  chopper: ^3.0.0
  logging: ^0.11.3+2
  built_value: ^6.7.0
dev_dependencies:
  build_runner: ^1.5.0
  json_serializable: ^3.0.0
  chopper_generator: ^3.0.0
  built_value_generator: ^6.7.0
  flutter_test:
    sdk: flutter

# device_info 0.4.0+2
flutter:
  uses-material-design: true
